package model;

// Generated 2012-6-18 10:35:42 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.annotations.Type;

import com.xcesys.extras.core.dao.model.VersionableEntity;


/**
 * TdoOrderDetails generated by hbm2java
 */
@Entity
@Table(name = "TDO_ORDER_DETAILS")
public class TdoOrderDetails extends VersionableEntity implements java.io.Serializable {

	private static final long serialVersionUID = -2178655630950409453L;

	private Long id;
	private TdoOrderMaster tdoOrderMaster;
	private Long tdoOrderMasterId; //TODO,DetailsAware
	private Long skuId;
	private Integer orderLineno;
	private String lineStatus;
	private String lineStatusName;
	private String sku;
	private String skuDescrCn;
	private String skuDescrEn;
	private String alternativeSku;
	private String lotNo;
	private String lotatt01;
	private String lotatt02;
	private String lotatt03;
	private String lotatt04;
	private String lotatt05;
	private String lotatt06;
	private String lotatt07;
	private String lotatt08;
	private String lotatt09;
	private String lotatt10;
	private String lotatt11;
	private String lotatt12;
	private Long pickZoneId;
	private Long locationId;
	private String traceNo;
	private Long zonegroupId;
	private String locgroup1Code;
	private String locgroup2Code;
	private Double qtyOrdered;
	private Double qtySoftallocated;
	private Double qtyAllocated;
	private Double qtyPicked;
	private Double qtyShipped;
	private Double qtyOrderedEach;
	private Double qtySoftallocatedEach;
	private Double qtyAllocatedEach;
	private Double qtyPickedEach;
	private Double qtyShippedEach;
	private Long packId;
	private String uom;
	private String uomName;
	private Double netweight;
	private Double grossweight;
	private Double cubic;
	private Double price;
	private Long rotationId;
	private Long softallocationRuleId;
	private Long allocationRuleId;
	private Boolean onestepAllocationFlag;
	private Long kitSku;
	private Boolean commingleSku;
	private Integer kitReferenceNo;
	private String userdefine1;
	private String userdefine2;
	private String userdefine3;
	private String userdefine4;
	private String userdefine5;
	private String userdefine6;
	private String orderlineRefNo;
	private Boolean erpCancelFlag;
	private String createSource;
	private String DEdi01;
	private String DEdi02;
	private String DEdi03;
	private String DEdi04;
	private String DEdi05;
	private String DEdi06;
	private String DEdi07;
	private String DEdi08;
	private Double DEdi09;
	private Double DEdi10;
	private String DEdi11;
	private String DEdi12;
	private String DEdi13;
	private String DEdi14;
	private String DEdi15;
	private String DEdi16;
	private String DEdi17;
	private String DEdi18;
	private String DEdi19;
	private String DEdi20;
	private String notes;

	public TdoOrderDetails() {
	}

	public TdoOrderDetails(Long id) {
		this.id = id;
	}

	public TdoOrderDetails(TdoOrderMaster tdoOrderMaster, Long skuId, Integer orderLineno, String lineStatus, String sku,
			String skuDescrCn, String skuDescrEn, String alternativeSku, String lotNo, String lotatt01, String lotatt02, String lotatt03,
			String lotatt04, String lotatt05, String lotatt06, String lotatt07, String lotatt08, String lotatt09, String lotatt10,
			String lotatt11, String lotatt12, Long pickZoneId, Long locationId, String traceNo, Long zonegroupId, String locgroup1Code,
			String locgroup2Code, Double qtyOrdered, Double qtySoftallocated, Double qtyAllocated, Double qtyPicked, Double qtyShipped,
			Double qtyOrderedEach, Double qtySoftallocatedEach, Double qtyAllocatedEach, Double qtyPickedEach, Double qtyShippedEach,
			Long packId, String uom, Double netweight, Double grossweight, Double cubic, Double price, Long rotationId,
			Long softallocationRuleId, Long allocationRuleId, Boolean onestepAllocationFlag, Long kitSku, Boolean commingleSku,
			Integer kitReferenceNo, String userdefine1, String userdefine2, String userdefine3, String userdefine4, String userdefine5,
			String userdefine6, String orderlineRefNo, Boolean erpCancelFlag, String createSource, String DEdi01, String DEdi02,
			String DEdi03, String DEdi04, String DEdi05, String DEdi06, String DEdi07, String DEdi08, Double DEdi09, Double DEdi10,
			String DEdi11, String DEdi12, String DEdi13, String DEdi14, String DEdi15, String DEdi16, String DEdi17, String DEdi18,
			String DEdi19, String DEdi20, String notes) {
		this.tdoOrderMaster = tdoOrderMaster;
		this.skuId = skuId;
		this.orderLineno = orderLineno;
		this.lineStatus = lineStatus;
		this.sku = sku;
		this.skuDescrCn = skuDescrCn;
		this.skuDescrEn = skuDescrEn;
		this.alternativeSku = alternativeSku;
		this.lotNo = lotNo;
		this.lotatt01 = lotatt01;
		this.lotatt02 = lotatt02;
		this.lotatt03 = lotatt03;
		this.lotatt04 = lotatt04;
		this.lotatt05 = lotatt05;
		this.lotatt06 = lotatt06;
		this.lotatt07 = lotatt07;
		this.lotatt08 = lotatt08;
		this.lotatt09 = lotatt09;
		this.lotatt10 = lotatt10;
		this.lotatt11 = lotatt11;
		this.lotatt12 = lotatt12;
		this.pickZoneId = pickZoneId;
		this.locationId = locationId;
		this.traceNo = traceNo;
		this.zonegroupId = zonegroupId;
		this.locgroup1Code = locgroup1Code;
		this.locgroup2Code = locgroup2Code;
		this.qtyOrdered = qtyOrdered;
		this.qtySoftallocated = qtySoftallocated;
		this.qtyAllocated = qtyAllocated;
		this.qtyPicked = qtyPicked;
		this.qtyShipped = qtyShipped;
		this.qtyOrderedEach = qtyOrderedEach;
		this.qtySoftallocatedEach = qtySoftallocatedEach;
		this.qtyAllocatedEach = qtyAllocatedEach;
		this.qtyPickedEach = qtyPickedEach;
		this.qtyShippedEach = qtyShippedEach;
		this.packId = packId;
		this.uom = uom;
		this.netweight = netweight;
		this.grossweight = grossweight;
		this.cubic = cubic;
		this.price = price;
		this.rotationId = rotationId;
		this.softallocationRuleId = softallocationRuleId;
		this.allocationRuleId = allocationRuleId;
		this.onestepAllocationFlag = onestepAllocationFlag;
		this.kitSku = kitSku;
		this.commingleSku = commingleSku;
		this.kitReferenceNo = kitReferenceNo;
		this.userdefine1 = userdefine1;
		this.userdefine2 = userdefine2;
		this.userdefine3 = userdefine3;
		this.userdefine4 = userdefine4;
		this.userdefine5 = userdefine5;
		this.userdefine6 = userdefine6;
		this.orderlineRefNo = orderlineRefNo;
		this.erpCancelFlag = erpCancelFlag;
		this.createSource = createSource;
		this.DEdi01 = DEdi01;
		this.DEdi02 = DEdi02;
		this.DEdi03 = DEdi03;
		this.DEdi04 = DEdi04;
		this.DEdi05 = DEdi05;
		this.DEdi06 = DEdi06;
		this.DEdi07 = DEdi07;
		this.DEdi08 = DEdi08;
		this.DEdi09 = DEdi09;
		this.DEdi10 = DEdi10;
		this.DEdi11 = DEdi11;
		this.DEdi12 = DEdi12;
		this.DEdi13 = DEdi13;
		this.DEdi14 = DEdi14;
		this.DEdi15 = DEdi15;
		this.DEdi16 = DEdi16;
		this.DEdi17 = DEdi17;
		this.DEdi18 = DEdi18;
		this.DEdi19 = DEdi19;
		this.DEdi20 = DEdi20;
		this.notes = notes;
	}

	@GenericGenerator(name = "generator", strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator", parameters = @Parameter(name = "sequence_name", value = "seq_ORDER_DETAILS_id"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "ORDER_DETAILS_ID", unique = true, nullable = false, precision = 20, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "ORDER_ID")
	public Long getTdoOrderMasterId() {
		return tdoOrderMasterId;
	}

	public void setTdoOrderMasterId(Long tdoOrderMasterId) {
		this.tdoOrderMasterId = tdoOrderMasterId;
	}
	
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="ORDER_ID",insertable=false,updatable=false)
	public TdoOrderMaster getTdoOrderMaster() {
		return tdoOrderMaster;
	}

	public void setTdoOrderMaster(TdoOrderMaster tdoOrderMaster) {
		this.tdoOrderMaster = tdoOrderMaster;
	}

	@Column(name = "SKU_ID", precision = 20, scale = 0)
	public Long getSkuId() {
		return this.skuId;
	}

	public void setSkuId(Long skuId) {
		this.skuId = skuId;
	}

	@Column(name = "ORDER_LINENO", precision = 22, scale = 0)
	public Integer getOrderLineno() {
		return this.orderLineno;
	}

	public void setOrderLineno(Integer orderLineno) {
		this.orderLineno = orderLineno;
	}

	@Column(name = "LINE_STATUS", length = 20)
	public String getLineStatus() {
		return this.lineStatus;
	}

	public void setLineStatus(String lineStatus) {
		this.lineStatus = lineStatus;
	}
	@Transient
	public String getLineStatusName() {
		return lineStatusName;
	}

	public void setLineStatusName(String lineStatusName) {
		this.lineStatusName = lineStatusName;
	}

	@Column(name = "SKU", length = 50)
	public String getSku() {
		return this.sku;
	}

	public void setSku(String sku) {
		this.sku = sku;
	}

	@Column(name = "SKU_DESCR_CN", length = 100)
	public String getSkuDescrCn() {
		return this.skuDescrCn;
	}

	public void setSkuDescrCn(String skuDescrCn) {
		this.skuDescrCn = skuDescrCn;
	}

	@Column(name = "SKU_DESCR_EN", length = 100)
	public String getSkuDescrEn() {
		return this.skuDescrEn;
	}

	public void setSkuDescrEn(String skuDescrEn) {
		this.skuDescrEn = skuDescrEn;
	}

	@Column(name = "ALTERNATIVE_SKU", length = 100)
	public String getAlternativeSku() {
		return this.alternativeSku;
	}

	public void setAlternativeSku(String alternativeSku) {
		this.alternativeSku = alternativeSku;
	}

	@Column(name = "LOT_NO", length = 50)
	public String getLotNo() {
		return this.lotNo;
	}

	public void setLotNo(String lotNo) {
		this.lotNo = lotNo;
	}

	@Column(name = "LOTATT01", length = 50)
	public String getLotatt01() {
		return this.lotatt01;
	}

	public void setLotatt01(String lotatt01) {
		this.lotatt01 = lotatt01;
	}

	@Column(name = "LOTATT02", length = 50)
	public String getLotatt02() {
		return this.lotatt02;
	}

	public void setLotatt02(String lotatt02) {
		this.lotatt02 = lotatt02;
	}

	@Column(name = "LOTATT03", length = 50)
	public String getLotatt03() {
		return this.lotatt03;
	}

	public void setLotatt03(String lotatt03) {
		this.lotatt03 = lotatt03;
	}

	@Column(name = "LOTATT04", length = 200)
	public String getLotatt04() {
		return this.lotatt04;
	}

	public void setLotatt04(String lotatt04) {
		this.lotatt04 = lotatt04;
	}

	@Column(name = "LOTATT05", length = 200)
	public String getLotatt05() {
		return this.lotatt05;
	}

	public void setLotatt05(String lotatt05) {
		this.lotatt05 = lotatt05;
	}

	@Column(name = "LOTATT06", length = 200)
	public String getLotatt06() {
		return this.lotatt06;
	}

	public void setLotatt06(String lotatt06) {
		this.lotatt06 = lotatt06;
	}

	@Column(name = "LOTATT07", length = 200)
	public String getLotatt07() {
		return this.lotatt07;
	}

	public void setLotatt07(String lotatt07) {
		this.lotatt07 = lotatt07;
	}

	@Column(name = "LOTATT08", length = 200)
	public String getLotatt08() {
		return this.lotatt08;
	}

	public void setLotatt08(String lotatt08) {
		this.lotatt08 = lotatt08;
	}

	@Column(name = "LOTATT09", length = 200)
	public String getLotatt09() {
		return this.lotatt09;
	}

	public void setLotatt09(String lotatt09) {
		this.lotatt09 = lotatt09;
	}

	@Column(name = "LOTATT10", length = 200)
	public String getLotatt10() {
		return this.lotatt10;
	}

	public void setLotatt10(String lotatt10) {
		this.lotatt10 = lotatt10;
	}

	@Column(name = "LOTATT11", length = 200)
	public String getLotatt11() {
		return this.lotatt11;
	}

	public void setLotatt11(String lotatt11) {
		this.lotatt11 = lotatt11;
	}

	@Column(name = "LOTATT12", length = 200)
	public String getLotatt12() {
		return this.lotatt12;
	}

	public void setLotatt12(String lotatt12) {
		this.lotatt12 = lotatt12;
	}

	@Column(name = "PICK_ZONE_ID", precision = 20, scale = 0)
	public Long getPickZoneId() {
		return this.pickZoneId;
	}

	public void setPickZoneId(Long pickZoneId) {
		this.pickZoneId = pickZoneId;
	}

	@Column(name = "LOCATION_ID", precision = 20, scale = 0)
	public Long getLocationId() {
		return this.locationId;
	}

	public void setLocationId(Long locationId) {
		this.locationId = locationId;
	}

	@Column(name = "TRACE_NO", length = 50)
	public String getTraceNo() {
		return this.traceNo;
	}

	public void setTraceNo(String traceNo) {
		this.traceNo = traceNo;
	}

	@Column(name = "ZONEGROUP_ID", precision = 20, scale = 0)
	public Long getZonegroupId() {
		return zonegroupId;
	}

	public void setZonegroupId(Long zonegroupId) {
		this.zonegroupId = zonegroupId;
	}

	@Column(name = "LOCGROUP1_CODE", length = 50)
	public String getLocgroup1Code() {
		return this.locgroup1Code;
	}

	public void setLocgroup1Code(String locgroup1Code) {
		this.locgroup1Code = locgroup1Code;
	}

	@Column(name = "LOCGROUP2_CODE", length = 50)
	public String getLocgroup2Code() {
		return this.locgroup2Code;
	}

	public void setLocgroup2Code(String locgroup2Code) {
		this.locgroup2Code = locgroup2Code;
	}

	@Column(name = "QTY_ORDERED", precision = 18, scale = 8)
	public Double getQtyOrdered() {
		return this.qtyOrdered;
	}

	public void setQtyOrdered(Double qtyOrdered) {
		this.qtyOrdered = qtyOrdered;
	}

	@Column(name = "QTY_SOFTALLOCATED", precision = 18, scale = 8)
	public Double getQtySoftallocated() {
		return this.qtySoftallocated;
	}

	public void setQtySoftallocated(Double qtySoftallocated) {
		this.qtySoftallocated = qtySoftallocated;
	}

	@Column(name = "QTY_ALLOCATED", precision = 18, scale = 8)
	public Double getQtyAllocated() {
		return this.qtyAllocated;
	}

	public void setQtyAllocated(Double qtyAllocated) {
		this.qtyAllocated = qtyAllocated;
	}

	@Column(name = "QTY_PICKED", precision = 18, scale = 8)
	public Double getQtyPicked() {
		return this.qtyPicked;
	}

	public void setQtyPicked(Double qtyPicked) {
		this.qtyPicked = qtyPicked;
	}

	@Column(name = "QTY_SHIPPED", precision = 18, scale = 8)
	public Double getQtyShipped() {
		return this.qtyShipped;
	}

	public void setQtyShipped(Double qtyShipped) {
		this.qtyShipped = qtyShipped;
	}

	@Column(name = "QTY_ORDERED_EACH", precision = 18, scale = 8)
	public Double getQtyOrderedEach() {
		return this.qtyOrderedEach;
	}

	public void setQtyOrderedEach(Double qtyOrderedEach) {
		this.qtyOrderedEach = qtyOrderedEach;
	}

	@Column(name = "QTY_SOFTALLOCATED_EACH", precision = 18, scale = 8)
	public Double getQtySoftallocatedEach() {
		return this.qtySoftallocatedEach;
	}

	public void setQtySoftallocatedEach(Double qtySoftallocatedEach) {
		this.qtySoftallocatedEach = qtySoftallocatedEach;
	}

	@Column(name = "QTY_ALLOCATED_EACH", precision = 18, scale = 8)
	public Double getQtyAllocatedEach() {
		return this.qtyAllocatedEach;
	}

	public void setQtyAllocatedEach(Double qtyAllocatedEach) {
		this.qtyAllocatedEach = qtyAllocatedEach;
	}

	@Column(name = "QTY_PICKED_EACH", precision = 18, scale = 8)
	public Double getQtyPickedEach() {
		return this.qtyPickedEach;
	}

	public void setQtyPickedEach(Double qtyPickedEach) {
		this.qtyPickedEach = qtyPickedEach;
	}

	@Column(name = "QTY_SHIPPED_EACH", precision = 18, scale = 8)
	public Double getQtyShippedEach() {
		return this.qtyShippedEach;
	}

	public void setQtyShippedEach(Double qtyShippedEach) {
		this.qtyShippedEach = qtyShippedEach;
	}

	@Column(name = "PACK_ID", precision = 20, scale = 0)
	public Long getPackId() {
		return this.packId;
	}

	public void setPackId(Long packId) {
		this.packId = packId;
	}

	@Column(name = "UOM", length = 20)
	public String getUom() {
		return this.uom;
	}

	public void setUom(String uom) {
		this.uom = uom;
	}
	@Transient
	public String getUomName() {
		return uomName;
	}

	public void setUomName(String uomName) {
		this.uomName = uomName;
	}

	@Column(name = "NETWEIGHT", precision = 18, scale = 8)
	public Double getNetweight() {
		return this.netweight;
	}

	public void setNetweight(Double netweight) {
		this.netweight = netweight;
	}

	@Column(name = "GROSSWEIGHT", precision = 18, scale = 8)
	public Double getGrossweight() {
		return this.grossweight;
	}

	public void setGrossweight(Double grossweight) {
		this.grossweight = grossweight;
	}

	@Column(name = "CUBIC", precision = 18, scale = 8)
	public Double getCubic() {
		return this.cubic;
	}

	public void setCubic(Double cubic) {
		this.cubic = cubic;
	}

	@Column(name = "PRICE", precision = 18, scale = 8)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	@Column(name = "ROTATION_ID", precision = 20, scale = 0)
	public Long getRotationId() {
		return this.rotationId;
	}

	public void setRotationId(Long rotationId) {
		this.rotationId = rotationId;
	}

	@Column(name = "SOFTALLOCATION_RULE_ID", precision = 20, scale = 0)
	public Long getSoftallocationRuleId() {
		return this.softallocationRuleId;
	}

	public void setSoftallocationRuleId(Long softallocationRuleId) {
		this.softallocationRuleId = softallocationRuleId;
	}

	@Column(name = "ALLOCATION_RULE_ID", precision = 20, scale = 0)
	public Long getAllocationRuleId() {
		return this.allocationRuleId;
	}

	public void setAllocationRuleId(Long allocationRuleId) {
		this.allocationRuleId = allocationRuleId;
	}

	@Type(type = "yes_no")
	@Column(name = "ONESTEP_ALLOCATION_FLAG", length = 10)
	public Boolean getOnestepAllocationFlag() {
		return this.onestepAllocationFlag;
	}

	public void setOnestepAllocationFlag(Boolean onestepAllocationFlag) {
		this.onestepAllocationFlag = onestepAllocationFlag;
	}

	@Column(name = "KIT_SKU", precision = 20, scale = 0)
	public Long getKitSku() {
		return this.kitSku;
	}

	public void setKitSku(Long kitSku) {
		this.kitSku = kitSku;
	}

	@Type(type = "yes_no")
	@Column(name = "COMMINGLE_SKU", length = 10)
	public Boolean getCommingleSku() {
		return this.commingleSku;
	}

	public void setCommingleSku(Boolean commingleSku) {
		this.commingleSku = commingleSku;
	}

	@Column(name = "KIT_REFERENCE_NO", length = 200)
	public Integer getKitReferenceNo() {
		return this.kitReferenceNo;
	}

	public void setKitReferenceNo(Integer kitReferenceNo) {
		this.kitReferenceNo = kitReferenceNo;
	}

	@Column(name = "USERDEFINE1", length = 200)
	public String getUserdefine1() {
		return this.userdefine1;
	}

	public void setUserdefine1(String userdefine1) {
		this.userdefine1 = userdefine1;
	}

	@Column(name = "USERDEFINE2", length = 200)
	public String getUserdefine2() {
		return this.userdefine2;
	}

	public void setUserdefine2(String userdefine2) {
		this.userdefine2 = userdefine2;
	}

	@Column(name = "USERDEFINE3", length = 200)
	public String getUserdefine3() {
		return this.userdefine3;
	}

	public void setUserdefine3(String userdefine3) {
		this.userdefine3 = userdefine3;
	}

	@Column(name = "USERDEFINE4", length = 200)
	public String getUserdefine4() {
		return this.userdefine4;
	}

	public void setUserdefine4(String userdefine4) {
		this.userdefine4 = userdefine4;
	}

	@Column(name = "USERDEFINE5", length = 200)
	public String getUserdefine5() {
		return this.userdefine5;
	}

	public void setUserdefine5(String userdefine5) {
		this.userdefine5 = userdefine5;
	}

	@Column(name = "USERDEFINE6", length = 200)
	public String getUserdefine6() {
		return this.userdefine6;
	}

	public void setUserdefine6(String userdefine6) {
		this.userdefine6 = userdefine6;
	}

	@Column(name = "ORDERLINE_REF_NO", length = 50)
	public String getOrderlineRefNo() {
		return this.orderlineRefNo;
	}

	public void setOrderlineRefNo(String orderlineRefNo) {
		this.orderlineRefNo = orderlineRefNo;
	}

	@Type(type = "yes_no")
	@Column(name = "ERP_CANCEL_FLAG", length = 10)
	public Boolean getErpCancelFlag() {
		return this.erpCancelFlag;
	}

	public void setErpCancelFlag(Boolean erpCancelFlag) {
		this.erpCancelFlag = erpCancelFlag;
	}

	@Column(name = "CREATE_SOURCE", length = 50)
	public String getCreateSource() {
		return this.createSource;
	}

	public void setCreateSource(String createSource) {
		this.createSource = createSource;
	}

	@Column(name = "D_EDI_01", length = 200)
	public String getDEdi01() {
		return this.DEdi01;
	}

	public void setDEdi01(String DEdi01) {
		this.DEdi01 = DEdi01;
	}

	@Column(name = "D_EDI_02", length = 200)
	public String getDEdi02() {
		return this.DEdi02;
	}

	public void setDEdi02(String DEdi02) {
		this.DEdi02 = DEdi02;
	}

	@Column(name = "D_EDI_03", length = 200)
	public String getDEdi03() {
		return this.DEdi03;
	}

	public void setDEdi03(String DEdi03) {
		this.DEdi03 = DEdi03;
	}

	@Column(name = "D_EDI_04", length = 200)
	public String getDEdi04() {
		return this.DEdi04;
	}

	public void setDEdi04(String DEdi04) {
		this.DEdi04 = DEdi04;
	}

	@Column(name = "D_EDI_05", length = 200)
	public String getDEdi05() {
		return this.DEdi05;
	}

	public void setDEdi05(String DEdi05) {
		this.DEdi05 = DEdi05;
	}

	@Column(name = "D_EDI_06", length = 200)
	public String getDEdi06() {
		return this.DEdi06;
	}

	public void setDEdi06(String DEdi06) {
		this.DEdi06 = DEdi06;
	}

	@Column(name = "D_EDI_07", length = 200)
	public String getDEdi07() {
		return this.DEdi07;
	}

	public void setDEdi07(String DEdi07) {
		this.DEdi07 = DEdi07;
	}

	@Column(name = "D_EDI_08", length = 200)
	public String getDEdi08() {
		return this.DEdi08;
	}

	public void setDEdi08(String DEdi08) {
		this.DEdi08 = DEdi08;
	}

	@Column(name = "D_EDI_09", precision = 18, scale = 8)
	public Double getDEdi09() {
		return this.DEdi09;
	}

	public void setDEdi09(Double DEdi09) {
		this.DEdi09 = DEdi09;
	}

	@Column(name = "D_EDI_10", precision = 18, scale = 8)
	public Double getDEdi10() {
		return this.DEdi10;
	}

	public void setDEdi10(Double DEdi10) {
		this.DEdi10 = DEdi10;
	}

	@Column(name = "D_EDI_11", length = 200)
	public String getDEdi11() {
		return this.DEdi11;
	}

	public void setDEdi11(String DEdi11) {
		this.DEdi11 = DEdi11;
	}

	@Column(name = "D_EDI_12", length = 200)
	public String getDEdi12() {
		return this.DEdi12;
	}

	public void setDEdi12(String DEdi12) {
		this.DEdi12 = DEdi12;
	}

	@Column(name = "D_EDI_13", length = 200)
	public String getDEdi13() {
		return this.DEdi13;
	}

	public void setDEdi13(String DEdi13) {
		this.DEdi13 = DEdi13;
	}

	@Column(name = "D_EDI_14", length = 200)
	public String getDEdi14() {
		return this.DEdi14;
	}

	public void setDEdi14(String DEdi14) {
		this.DEdi14 = DEdi14;
	}

	@Column(name = "D_EDI_15", length = 200)
	public String getDEdi15() {
		return this.DEdi15;
	}

	public void setDEdi15(String DEdi15) {
		this.DEdi15 = DEdi15;
	}

	@Column(name = "D_EDI_16", length = 200)
	public String getDEdi16() {
		return this.DEdi16;
	}

	public void setDEdi16(String DEdi16) {
		this.DEdi16 = DEdi16;
	}

	@Column(name = "D_EDI_17", length = 200)
	public String getDEdi17() {
		return this.DEdi17;
	}

	public void setDEdi17(String DEdi17) {
		this.DEdi17 = DEdi17;
	}

	@Column(name = "D_EDI_18", length = 200)
	public String getDEdi18() {
		return this.DEdi18;
	}

	public void setDEdi18(String DEdi18) {
		this.DEdi18 = DEdi18;
	}

	@Column(name = "D_EDI_19", length = 200)
	public String getDEdi19() {
		return this.DEdi19;
	}

	public void setDEdi19(String DEdi19) {
		this.DEdi19 = DEdi19;
	}

	@Column(name = "D_EDI_20", length = 200)
	public String getDEdi20() {
		return this.DEdi20;
	}

	public void setDEdi20(String DEdi20) {
		this.DEdi20 = DEdi20;
	}

	@Column(name = "NOTES", length = 4000)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}
}
