package model;

// Generated 2012-6-18 10:35:42 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.annotations.Type;

import com.xcesys.extras.core.dao.model.VersionableEntity;


/**
 * TdoOrderMaster generated by hbm2java
 */
@Entity
@Table(name = "TDO_ORDER_MASTER")
public class TdoOrderMaster extends VersionableEntity implements java.io.Serializable {

	private static final long serialVersionUID = -7154348168527337837L;

	private Long id;
	private Long customerId;
	private String orderNo;
	private String orderType;
	private String orderTypeName;
	private String orderStatus;
	private String orderStatusName;
	private Long warehouseId;
	private Date orderTime;
	private Date expectedShipmenttime1;
	private Date expectedShipmenttime2;
	private Date requiredDeliverytime;
	private String soReference1;
	private String soReference2;
	private String soReference3;
	private String soReference4;
	private String soReference5;
	private String priority;
	private String deliveryTerms;
	private String deliveryTermsDescr;
	private String paymentTerms;
	private String paymentTermsDescr;
	private Long zonegroupId;
	private String transportation;
	private String door;
	private String route;
	private String stop;
	private String placeOfDischarge;
	private String placeOfDelivery;
	private String placeOfLoading;
	private Boolean pickingPrintFlag;
	private Date lastShipmentTime;
	private String releaseStatus;
	private Boolean orderPrintFlag;
	private Boolean rfGettaskFlag;
	private String requireDeliveryNo;
	private Boolean singleMatchFlag;
	private String consigneeCode;
	private String consigneeName;
	private String coAddress1;
	private String coAddress2;
	private String coAddress3;
	private String coAddress4;
	private String coCountry;
	private String coProvince;
	private String coCity;
	private String coZip;
	private String coContact;
	private String coTel1;
	private String coTel2;
	private String coFax;
	private String coMail;
	private String billingCode;
	private String billingName;
	private String BAddress1;
	private String BAddress2;
	private String BAddress3;
	private String BAddress4;
	private String BCountry;
	private String BProvince;
	private String BCity;
	private String BZip;
	private String BContact;
	private String BTel1;
	private String BTel2;
	private String BFax;
	private String BMail;
	private String carrierCode;
	private String carrierName;
	private String caAddress1;
	private String caAddress2;
	private String caAddress3;
	private String caAddress4;
	private String caCountry;
	private String caProvince;
	private String caCity;
	private String caZip;
	private String caContact;
	private String caTel1;
	private String caTel2;
	private String caFax;
	private String caMail;
	private String issuepartyCode;
	private String issuepartyName;
	private String IAddress1;
	private String IAddress2;
	private String IAddress3;
	private String IAddress4;
	private String ICountry;
	private String IProvince;
	private String ICity;
	private String IZip;
	private String IContact;
	private String ITel1;
	private String ITel2;
	private String IFax;
	private String IMail;
	private String createSource;
	private Boolean ediSendFlag;
	private Date ediSendTime;
	private Date ediSendTime2;
	private Date ediSendTime3;
	private Date ediSendTime4;
	private Date ediSendTime5;
	private Boolean erpCancelFlag;
	private String HEdi01;
	private String HEdi02;
	private String HEdi03;
	private String HEdi04;
	private String HEdi05;
	private String HEdi06;
	private String HEdi07;
	private String HEdi08;
	private Double HEdi09;
	private Double HEdi10;
	private String userdefine1;
	private String userdefine2;
	private String userdefine3;
	private String userdefine4;
	private String userdefine5;
	private String userdefine6;
	private String notes;

	private Set<TdoOrderDetails> tdoOrderDetailses = new HashSet<TdoOrderDetails>(0);

	public TdoOrderMaster() {
	}

	public TdoOrderMaster(Long customerId, String orderNo, String orderType, String orderStatus, Long warehouseId, Date orderTime,
			Date expectedShipmenttime1, Date expectedShipmenttime2, Date requiredDeliverytime, String soReference1, String soReference2,
			String soReference3, String soReference4, String soReference5, String priority, String deliveryTerms,
			String deliveryTermsDescr, String paymentTerms, String paymentTermsDescr, Long zonegroupId, String transportation, String door,
			String route, String stop, String placeOfDischarge, String placeOfDelivery, String placeOfLoading, Boolean pickingPrintFlag,
			Date lastShipmentTime, String releaseStatus, Boolean orderPrintFlag, Boolean rfGettaskFlag, String requireDeliveryNo,
			Boolean singleMatchFlag, String consigneeCode, String consigneeName, String coAddress1, String coAddress2, String coAddress3,
			String coAddress4, String coCountry, String coProvince, String coCity, String coZip, String coContact, String coTel1,
			String coTel2, String coFax, String coMail, String billingCode, String billingName, String BAddress1, String BAddress2,
			String BAddress3, String BAddress4, String BCountry, String BProvince, String BCity, String BZip, String BContact,
			String BTel1, String BTel2, String BFax, String BMail, String carrierCode, String carrierName, String caAddress1,
			String caAddress2, String caAddress3, String caAddress4, String caCountry, String caProvince, String caCity, String caZip,
			String caContact, String caTel1, String caTel2, String caFax, String caMail, String issuepartyCode, String issuepartyName,
			String IAddress1, String IAddress2, String IAddress3, String IAddress4, String ICountry, String IProvince, String ICity,
			String IZip, String IContact, String ITel1, String ITel2, String IFax, String IMail, String createSource, Boolean ediSendFlag,
			Date ediSendTime, Date ediSendTime2, Date ediSendTime3, Date ediSendTime4, Date ediSendTime5, Boolean erpCancelFlag,
			String HEdi01, String HEdi02, String HEdi03, String HEdi04, String HEdi05, String HEdi06, String HEdi07, String HEdi08,
			Double HEdi09, Double HEdi10, String userdefine1, String userdefine2, String userdefine3, String userdefine4,
			String userdefine5, String userdefine6, String notes, Set<TdoOrderDetails> tdoOrderDetailses) {
		this.customerId = customerId;
		this.orderNo = orderNo;
		this.orderType = orderType;
		this.orderStatus = orderStatus;
		this.warehouseId = warehouseId;
		this.orderTime = orderTime;
		this.expectedShipmenttime1 = expectedShipmenttime1;
		this.expectedShipmenttime2 = expectedShipmenttime2;
		this.requiredDeliverytime = requiredDeliverytime;
		this.soReference1 = soReference1;
		this.soReference2 = soReference2;
		this.soReference3 = soReference3;
		this.soReference4 = soReference4;
		this.soReference5 = soReference5;
		this.priority = priority;
		this.deliveryTerms = deliveryTerms;
		this.deliveryTermsDescr = deliveryTermsDescr;
		this.paymentTerms = paymentTerms;
		this.paymentTermsDescr = paymentTermsDescr;
		this.zonegroupId = zonegroupId;
		this.transportation = transportation;
		this.door = door;
		this.route = route;
		this.stop = stop;
		this.placeOfDischarge = placeOfDischarge;
		this.placeOfDelivery = placeOfDelivery;
		this.placeOfLoading = placeOfLoading;
		this.pickingPrintFlag = pickingPrintFlag;
		this.lastShipmentTime = lastShipmentTime;
		this.releaseStatus = releaseStatus;
		this.orderPrintFlag = orderPrintFlag;
		this.rfGettaskFlag = rfGettaskFlag;
		this.requireDeliveryNo = requireDeliveryNo;
		this.singleMatchFlag = singleMatchFlag;
		this.consigneeCode = consigneeCode;
		this.consigneeName = consigneeName;
		this.coAddress1 = coAddress1;
		this.coAddress2 = coAddress2;
		this.coAddress3 = coAddress3;
		this.coAddress4 = coAddress4;
		this.coCountry = coCountry;
		this.coProvince = coProvince;
		this.coCity = coCity;
		this.coZip = coZip;
		this.coContact = coContact;
		this.coTel1 = coTel1;
		this.coTel2 = coTel2;
		this.coFax = coFax;
		this.coMail = coMail;
		this.billingCode = billingCode;
		this.billingName = billingName;
		this.BAddress1 = BAddress1;
		this.BAddress2 = BAddress2;
		this.BAddress3 = BAddress3;
		this.BAddress4 = BAddress4;
		this.BCountry = BCountry;
		this.BProvince = BProvince;
		this.BCity = BCity;
		this.BZip = BZip;
		this.BContact = BContact;
		this.BTel1 = BTel1;
		this.BTel2 = BTel2;
		this.BFax = BFax;
		this.BMail = BMail;
		this.carrierCode = carrierCode;
		this.carrierName = carrierName;
		this.caAddress1 = caAddress1;
		this.caAddress2 = caAddress2;
		this.caAddress3 = caAddress3;
		this.caAddress4 = caAddress4;
		this.caCountry = caCountry;
		this.caProvince = caProvince;
		this.caCity = caCity;
		this.caZip = caZip;
		this.caContact = caContact;
		this.caTel1 = caTel1;
		this.caTel2 = caTel2;
		this.caFax = caFax;
		this.caMail = caMail;
		this.issuepartyCode = issuepartyCode;
		this.issuepartyName = issuepartyName;
		this.IAddress1 = IAddress1;
		this.IAddress2 = IAddress2;
		this.IAddress3 = IAddress3;
		this.IAddress4 = IAddress4;
		this.ICountry = ICountry;
		this.IProvince = IProvince;
		this.ICity = ICity;
		this.IZip = IZip;
		this.IContact = IContact;
		this.ITel1 = ITel1;
		this.ITel2 = ITel2;
		this.IFax = IFax;
		this.IMail = IMail;
		this.createSource = createSource;
		this.ediSendFlag = ediSendFlag;
		this.ediSendTime = ediSendTime;
		this.ediSendTime2 = ediSendTime2;
		this.ediSendTime3 = ediSendTime3;
		this.ediSendTime4 = ediSendTime4;
		this.ediSendTime5 = ediSendTime5;
		this.erpCancelFlag = erpCancelFlag;
		this.HEdi01 = HEdi01;
		this.HEdi02 = HEdi02;
		this.HEdi03 = HEdi03;
		this.HEdi04 = HEdi04;
		this.HEdi05 = HEdi05;
		this.HEdi06 = HEdi06;
		this.HEdi07 = HEdi07;
		this.HEdi08 = HEdi08;
		this.HEdi09 = HEdi09;
		this.HEdi10 = HEdi10;
		this.userdefine1 = userdefine1;
		this.userdefine2 = userdefine2;
		this.userdefine3 = userdefine3;
		this.userdefine4 = userdefine4;
		this.userdefine5 = userdefine5;
		this.userdefine6 = userdefine6;
		this.notes = notes;
		this.tdoOrderDetailses = tdoOrderDetailses;
	}

	@GenericGenerator(name = "generator", strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator", parameters = @Parameter(name = "sequence_name", value = "seq_ORDER_id"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "ORDER_ID", unique = true, nullable = false, precision = 20, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "CUSTOMER_ID", precision = 20, scale = 0)
	public Long getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Long customerId) {
		this.customerId = customerId;
	}

	@Column(name = "ORDER_NO", length = 50)
	public String getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

	@Column(name = "ORDER_TYPE", length = 50)
	public String getOrderType() {
		return this.orderType;
	}

	public void setOrderType(String orderType) {
		this.orderType = orderType;
	}

	@Transient
	public String getOrderTypeName() {
		return orderTypeName;
	}

	public void setOrderTypeName(String orderTypeName) {
		this.orderTypeName = orderTypeName;
	}

	@Column(name = "ORDER_STATUS", length = 20)
	public String getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(String orderStatus) {
		this.orderStatus = orderStatus;
	}

	@Transient
	public String getOrderStatusName() {
		return orderStatusName;
	}

	public void setOrderStatusName(String orderStatusName) {
		this.orderStatusName = orderStatusName;
	}

	@Column(name = "WAREHOUSE_ID", precision = 20, scale = 0)
	public Long getWarehouseId() {
		return this.warehouseId;
	}

	public void setWarehouseId(Long warehouseId) {
		this.warehouseId = warehouseId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ORDER_TIME", length = 7)
	public Date getOrderTime() {
		return this.orderTime;
	}

	public void setOrderTime(Date orderTime) {
		this.orderTime = orderTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EXPECTED_SHIPMENTTIME1", length = 7)
	public Date getExpectedShipmenttime1() {
		return this.expectedShipmenttime1;
	}

	public void setExpectedShipmenttime1(Date expectedShipmenttime1) {
		this.expectedShipmenttime1 = expectedShipmenttime1;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EXPECTED_SHIPMENTTIME2", length = 7)
	public Date getExpectedShipmenttime2() {
		return this.expectedShipmenttime2;
	}

	public void setExpectedShipmenttime2(Date expectedShipmenttime2) {
		this.expectedShipmenttime2 = expectedShipmenttime2;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REQUIRED_DELIVERYTIME", length = 7)
	public Date getRequiredDeliverytime() {
		return this.requiredDeliverytime;
	}

	public void setRequiredDeliverytime(Date requiredDeliverytime) {
		this.requiredDeliverytime = requiredDeliverytime;
	}

	@Column(name = "SO_REFERENCE1", length = 100)
	public String getSoReference1() {
		return this.soReference1;
	}

	public void setSoReference1(String soReference1) {
		this.soReference1 = soReference1;
	}

	@Column(name = "SO_REFERENCE2", length = 100)
	public String getSoReference2() {
		return this.soReference2;
	}

	public void setSoReference2(String soReference2) {
		this.soReference2 = soReference2;
	}

	@Column(name = "SO_REFERENCE3", length = 100)
	public String getSoReference3() {
		return this.soReference3;
	}

	public void setSoReference3(String soReference3) {
		this.soReference3 = soReference3;
	}

	@Column(name = "SO_REFERENCE4", length = 100)
	public String getSoReference4() {
		return this.soReference4;
	}

	public void setSoReference4(String soReference4) {
		this.soReference4 = soReference4;
	}

	@Column(name = "SO_REFERENCE5", length = 100)
	public String getSoReference5() {
		return this.soReference5;
	}

	public void setSoReference5(String soReference5) {
		this.soReference5 = soReference5;
	}

	@Column(name = "PRIORITY", length = 50)
	public String getPriority() {
		return this.priority;
	}

	public void setPriority(String priority) {
		this.priority = priority;
	}

	@Column(name = "DELIVERY_TERMS", length = 50)
	public String getDeliveryTerms() {
		return this.deliveryTerms;
	}

	public void setDeliveryTerms(String deliveryTerms) {
		this.deliveryTerms = deliveryTerms;
	}

	@Column(name = "DELIVERY_TERMS_DESCR", length = 200)
	public String getDeliveryTermsDescr() {
		return this.deliveryTermsDescr;
	}

	public void setDeliveryTermsDescr(String deliveryTermsDescr) {
		this.deliveryTermsDescr = deliveryTermsDescr;
	}

	@Column(name = "PAYMENT_TERMS", length = 50)
	public String getPaymentTerms() {
		return this.paymentTerms;
	}

	public void setPaymentTerms(String paymentTerms) {
		this.paymentTerms = paymentTerms;
	}

	@Column(name = "PAYMENT_TERMS_DESCR", length = 200)
	public String getPaymentTermsDescr() {
		return this.paymentTermsDescr;
	}

	public void setPaymentTermsDescr(String paymentTermsDescr) {
		this.paymentTermsDescr = paymentTermsDescr;
	}

	@Column(name = "ZONEGROUP_ID", precision = 20, scale = 0)
	public Long getZonegroupId() {
		return this.zonegroupId;
	}

	public void setZonegroupId(Long zonegroupId) {
		this.zonegroupId = zonegroupId;
	}

	@Column(name = "TRANSPORTATION", length = 100)
	public String getTransportation() {
		return this.transportation;
	}

	public void setTransportation(String transportation) {
		this.transportation = transportation;
	}

	@Column(name = "DOOR", length = 50)
	public String getDoor() {
		return this.door;
	}

	public void setDoor(String door) {
		this.door = door;
	}

	@Column(name = "ROUTE", length = 50)
	public String getRoute() {
		return this.route;
	}

	public void setRoute(String route) {
		this.route = route;
	}

	@Column(name = "STOP", length = 50)
	public String getStop() {
		return this.stop;
	}

	public void setStop(String stop) {
		this.stop = stop;
	}

	@Column(name = "PLACE_OF_DISCHARGE", length = 100)
	public String getPlaceOfDischarge() {
		return this.placeOfDischarge;
	}

	public void setPlaceOfDischarge(String placeOfDischarge) {
		this.placeOfDischarge = placeOfDischarge;
	}

	@Column(name = "PLACE_OF_DELIVERY", length = 100)
	public String getPlaceOfDelivery() {
		return this.placeOfDelivery;
	}

	public void setPlaceOfDelivery(String placeOfDelivery) {
		this.placeOfDelivery = placeOfDelivery;
	}

	@Column(name = "PLACE_OF_LOADING", length = 100)
	public String getPlaceOfLoading() {
		return this.placeOfLoading;
	}

	public void setPlaceOfLoading(String placeOfLoading) {
		this.placeOfLoading = placeOfLoading;
	}

	@Type(type = "yes_no")
	@Column(name = "PICKING_PRINT_FLAG", length = 10)
	public Boolean getPickingPrintFlag() {
		return this.pickingPrintFlag;
	}

	public void setPickingPrintFlag(Boolean pickingPrintFlag) {
		this.pickingPrintFlag = pickingPrintFlag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_SHIPMENT_TIME", length = 7)
	public Date getLastShipmentTime() {
		return this.lastShipmentTime;
	}

	public void setLastShipmentTime(Date lastShipmentTime) {
		this.lastShipmentTime = lastShipmentTime;
	}

	@Column(name = "RELEASE_STATUS", length = 10)
	public String getReleaseStatus() {
		return this.releaseStatus;
	}

	public void setReleaseStatus(String releaseStatus) {
		this.releaseStatus = releaseStatus;
	}

	@Type(type = "yes_no")
	@Column(name = "ORDER_PRINT_FLAG", length = 10)
	public Boolean getOrderPrintFlag() {
		return this.orderPrintFlag;
	}

	public void setOrderPrintFlag(Boolean orderPrintFlag) {
		this.orderPrintFlag = orderPrintFlag;
	}

	@Type(type = "yes_no")
	@Column(name = "RF_GETTASK_FLAG", length = 10)
	public Boolean getRfGettaskFlag() {
		return this.rfGettaskFlag;
	}

	public void setRfGettaskFlag(Boolean rfGettaskFlag) {
		this.rfGettaskFlag = rfGettaskFlag;
	}

	@Column(name = "REQUIRE_DELIVERY_NO", length = 50)
	public String getRequireDeliveryNo() {
		return this.requireDeliveryNo;
	}

	public void setRequireDeliveryNo(String requireDeliveryNo) {
		this.requireDeliveryNo = requireDeliveryNo;
	}

	@Type(type = "yes_no")
	@Column(name = "SINGLE_MATCH_FLAG", length = 10)
	public Boolean getSingleMatchFlag() {
		return this.singleMatchFlag;
	}

	public void setSingleMatchFlag(Boolean singleMatchFlag) {
		this.singleMatchFlag = singleMatchFlag;
	}

	@Column(name = "CONSIGNEE_CODE", length = 50)
	public String getConsigneeCode() {
		return this.consigneeCode;
	}

	public void setConsigneeCode(String consigneeCode) {
		this.consigneeCode = consigneeCode;
	}

	@Column(name = "CONSIGNEE_NAME", length = 200)
	public String getConsigneeName() {
		return this.consigneeName;
	}

	public void setConsigneeName(String consigneeName) {
		this.consigneeName = consigneeName;
	}

	@Column(name = "CO_ADDRESS1", length = 500)
	public String getCoAddress1() {
		return this.coAddress1;
	}

	public void setCoAddress1(String coAddress1) {
		this.coAddress1 = coAddress1;
	}

	@Column(name = "CO_ADDRESS2", length = 500)
	public String getCoAddress2() {
		return this.coAddress2;
	}

	public void setCoAddress2(String coAddress2) {
		this.coAddress2 = coAddress2;
	}

	@Column(name = "CO_ADDRESS3", length = 500)
	public String getCoAddress3() {
		return this.coAddress3;
	}

	public void setCoAddress3(String coAddress3) {
		this.coAddress3 = coAddress3;
	}

	@Column(name = "CO_ADDRESS4", length = 500)
	public String getCoAddress4() {
		return this.coAddress4;
	}

	public void setCoAddress4(String coAddress4) {
		this.coAddress4 = coAddress4;
	}

	@Column(name = "CO_COUNTRY", length = 100)
	public String getCoCountry() {
		return this.coCountry;
	}

	public void setCoCountry(String coCountry) {
		this.coCountry = coCountry;
	}

	@Column(name = "CO_PROVINCE", length = 50)
	public String getCoProvince() {
		return this.coProvince;
	}

	public void setCoProvince(String coProvince) {
		this.coProvince = coProvince;
	}

	@Column(name = "CO_CITY", length = 100)
	public String getCoCity() {
		return this.coCity;
	}

	public void setCoCity(String coCity) {
		this.coCity = coCity;
	}

	@Column(name = "CO_ZIP", length = 20)
	public String getCoZip() {
		return this.coZip;
	}

	public void setCoZip(String coZip) {
		this.coZip = coZip;
	}

	@Column(name = "CO_CONTACT", length = 200)
	public String getCoContact() {
		return this.coContact;
	}

	public void setCoContact(String coContact) {
		this.coContact = coContact;
	}

	@Column(name = "CO_TEL1", length = 50)
	public String getCoTel1() {
		return this.coTel1;
	}

	public void setCoTel1(String coTel1) {
		this.coTel1 = coTel1;
	}

	@Column(name = "CO_TEL2", length = 50)
	public String getCoTel2() {
		return this.coTel2;
	}

	public void setCoTel2(String coTel2) {
		this.coTel2 = coTel2;
	}

	@Column(name = "CO_FAX", length = 50)
	public String getCoFax() {
		return this.coFax;
	}

	public void setCoFax(String coFax) {
		this.coFax = coFax;
	}

	@Column(name = "CO_MAIL", length = 200)
	public String getCoMail() {
		return this.coMail;
	}

	public void setCoMail(String coMail) {
		this.coMail = coMail;
	}

	@Column(name = "BILLING_CODE", length = 50)
	public String getBillingCode() {
		return this.billingCode;
	}

	public void setBillingCode(String billingCode) {
		this.billingCode = billingCode;
	}

	@Column(name = "BILLING_NAME", length = 200)
	public String getBillingName() {
		return this.billingName;
	}

	public void setBillingName(String billingName) {
		this.billingName = billingName;
	}

	@Column(name = "B_ADDRESS1", length = 500)
	public String getBAddress1() {
		return this.BAddress1;
	}

	public void setBAddress1(String BAddress1) {
		this.BAddress1 = BAddress1;
	}

	@Column(name = "B_ADDRESS2", length = 500)
	public String getBAddress2() {
		return this.BAddress2;
	}

	public void setBAddress2(String BAddress2) {
		this.BAddress2 = BAddress2;
	}

	@Column(name = "B_ADDRESS3", length = 500)
	public String getBAddress3() {
		return this.BAddress3;
	}

	public void setBAddress3(String BAddress3) {
		this.BAddress3 = BAddress3;
	}

	@Column(name = "B_ADDRESS4", length = 500)
	public String getBAddress4() {
		return this.BAddress4;
	}

	public void setBAddress4(String BAddress4) {
		this.BAddress4 = BAddress4;
	}

	@Column(name = "B_COUNTRY", length = 100)
	public String getBCountry() {
		return this.BCountry;
	}

	public void setBCountry(String BCountry) {
		this.BCountry = BCountry;
	}

	@Column(name = "B_PROVINCE", length = 50)
	public String getBProvince() {
		return this.BProvince;
	}

	public void setBProvince(String BProvince) {
		this.BProvince = BProvince;
	}

	@Column(name = "B_CITY", length = 100)
	public String getBCity() {
		return this.BCity;
	}

	public void setBCity(String BCity) {
		this.BCity = BCity;
	}

	@Column(name = "B_ZIP", length = 20)
	public String getBZip() {
		return this.BZip;
	}

	public void setBZip(String BZip) {
		this.BZip = BZip;
	}

	@Column(name = "B_CONTACT", length = 200)
	public String getBContact() {
		return this.BContact;
	}

	public void setBContact(String BContact) {
		this.BContact = BContact;
	}

	@Column(name = "B_TEL1", length = 50)
	public String getBTel1() {
		return this.BTel1;
	}

	public void setBTel1(String BTel1) {
		this.BTel1 = BTel1;
	}

	@Column(name = "B_TEL2", length = 50)
	public String getBTel2() {
		return this.BTel2;
	}

	public void setBTel2(String BTel2) {
		this.BTel2 = BTel2;
	}

	@Column(name = "B_FAX", length = 50)
	public String getBFax() {
		return this.BFax;
	}

	public void setBFax(String BFax) {
		this.BFax = BFax;
	}

	@Column(name = "B_MAIL", length = 200)
	public String getBMail() {
		return this.BMail;
	}

	public void setBMail(String BMail) {
		this.BMail = BMail;
	}

	@Column(name = "CARRIER_CODE", length = 50)
	public String getCarrierCode() {
		return this.carrierCode;
	}

	public void setCarrierCode(String carrierCode) {
		this.carrierCode = carrierCode;
	}

	@Column(name = "CARRIER_NAME", length = 200)
	public String getCarrierName() {
		return this.carrierName;
	}

	public void setCarrierName(String carrierName) {
		this.carrierName = carrierName;
	}

	@Column(name = "CA_ADDRESS1", length = 500)
	public String getCaAddress1() {
		return this.caAddress1;
	}

	public void setCaAddress1(String caAddress1) {
		this.caAddress1 = caAddress1;
	}

	@Column(name = "CA_ADDRESS2", length = 500)
	public String getCaAddress2() {
		return this.caAddress2;
	}

	public void setCaAddress2(String caAddress2) {
		this.caAddress2 = caAddress2;
	}

	@Column(name = "CA_ADDRESS3", length = 500)
	public String getCaAddress3() {
		return this.caAddress3;
	}

	public void setCaAddress3(String caAddress3) {
		this.caAddress3 = caAddress3;
	}

	@Column(name = "CA_ADDRESS4", length = 500)
	public String getCaAddress4() {
		return this.caAddress4;
	}

	public void setCaAddress4(String caAddress4) {
		this.caAddress4 = caAddress4;
	}

	@Column(name = "CA_COUNTRY", length = 100)
	public String getCaCountry() {
		return this.caCountry;
	}

	public void setCaCountry(String caCountry) {
		this.caCountry = caCountry;
	}

	@Column(name = "CA_PROVINCE", length = 50)
	public String getCaProvince() {
		return this.caProvince;
	}

	public void setCaProvince(String caProvince) {
		this.caProvince = caProvince;
	}

	@Column(name = "CA_CITY", length = 100)
	public String getCaCity() {
		return this.caCity;
	}

	public void setCaCity(String caCity) {
		this.caCity = caCity;
	}

	@Column(name = "CA_ZIP", length = 20)
	public String getCaZip() {
		return this.caZip;
	}

	public void setCaZip(String caZip) {
		this.caZip = caZip;
	}

	@Column(name = "CA_CONTACT", length = 200)
	public String getCaContact() {
		return this.caContact;
	}

	public void setCaContact(String caContact) {
		this.caContact = caContact;
	}

	@Column(name = "CA_TEL1", length = 50)
	public String getCaTel1() {
		return this.caTel1;
	}

	public void setCaTel1(String caTel1) {
		this.caTel1 = caTel1;
	}

	@Column(name = "CA_TEL2", length = 50)
	public String getCaTel2() {
		return this.caTel2;
	}

	public void setCaTel2(String caTel2) {
		this.caTel2 = caTel2;
	}

	@Column(name = "CA_FAX", length = 50)
	public String getCaFax() {
		return this.caFax;
	}

	public void setCaFax(String caFax) {
		this.caFax = caFax;
	}

	@Column(name = "CA_MAIL", length = 200)
	public String getCaMail() {
		return this.caMail;
	}

	public void setCaMail(String caMail) {
		this.caMail = caMail;
	}

	@Column(name = "ISSUEPARTY_CODE", length = 50)
	public String getIssuepartyCode() {
		return this.issuepartyCode;
	}

	public void setIssuepartyCode(String issuepartyCode) {
		this.issuepartyCode = issuepartyCode;
	}

	@Column(name = "ISSUEPARTY_NAME", length = 200)
	public String getIssuepartyName() {
		return this.issuepartyName;
	}

	public void setIssuepartyName(String issuepartyName) {
		this.issuepartyName = issuepartyName;
	}

	@Column(name = "I_ADDRESS1", length = 500)
	public String getIAddress1() {
		return this.IAddress1;
	}

	public void setIAddress1(String IAddress1) {
		this.IAddress1 = IAddress1;
	}

	@Column(name = "I_ADDRESS2", length = 500)
	public String getIAddress2() {
		return this.IAddress2;
	}

	public void setIAddress2(String IAddress2) {
		this.IAddress2 = IAddress2;
	}

	@Column(name = "I_ADDRESS3", length = 500)
	public String getIAddress3() {
		return this.IAddress3;
	}

	public void setIAddress3(String IAddress3) {
		this.IAddress3 = IAddress3;
	}

	@Column(name = "I_ADDRESS4", length = 500)
	public String getIAddress4() {
		return this.IAddress4;
	}

	public void setIAddress4(String IAddress4) {
		this.IAddress4 = IAddress4;
	}

	@Column(name = "I_COUNTRY", length = 100)
	public String getICountry() {
		return this.ICountry;
	}

	public void setICountry(String ICountry) {
		this.ICountry = ICountry;
	}

	@Column(name = "I_PROVINCE", length = 50)
	public String getIProvince() {
		return this.IProvince;
	}

	public void setIProvince(String IProvince) {
		this.IProvince = IProvince;
	}

	@Column(name = "I_CITY", length = 100)
	public String getICity() {
		return this.ICity;
	}

	public void setICity(String ICity) {
		this.ICity = ICity;
	}

	@Column(name = "I_ZIP", length = 20)
	public String getIZip() {
		return this.IZip;
	}

	public void setIZip(String IZip) {
		this.IZip = IZip;
	}

	@Column(name = "I_CONTACT", length = 200)
	public String getIContact() {
		return this.IContact;
	}

	public void setIContact(String IContact) {
		this.IContact = IContact;
	}

	@Column(name = "I_TEL1", length = 50)
	public String getITel1() {
		return this.ITel1;
	}

	public void setITel1(String ITel1) {
		this.ITel1 = ITel1;
	}

	@Column(name = "I_TEL2", length = 50)
	public String getITel2() {
		return this.ITel2;
	}

	public void setITel2(String ITel2) {
		this.ITel2 = ITel2;
	}

	@Column(name = "I_FAX", length = 50)
	public String getIFax() {
		return this.IFax;
	}

	public void setIFax(String IFax) {
		this.IFax = IFax;
	}

	@Column(name = "I_MAIL", length = 200)
	public String getIMail() {
		return this.IMail;
	}

	public void setIMail(String IMail) {
		this.IMail = IMail;
	}

	@Column(name = "CREATE_SOURCE", length = 50)
	public String getCreateSource() {
		return this.createSource;
	}

	public void setCreateSource(String createSource) {
		this.createSource = createSource;
	}

	@Type(type = "yes_no")
	@Column(name = "EDI_SEND_FLAG", length = 10)
	public Boolean getEdiSendFlag() {
		return this.ediSendFlag;
	}

	public void setEdiSendFlag(Boolean ediSendFlag) {
		this.ediSendFlag = ediSendFlag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EDI_SEND_TIME", length = 7)
	public Date getEdiSendTime() {
		return this.ediSendTime;
	}

	public void setEdiSendTime(Date ediSendTime) {
		this.ediSendTime = ediSendTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EDI_SEND_TIME2", length = 7)
	public Date getEdiSendTime2() {
		return this.ediSendTime2;
	}

	public void setEdiSendTime2(Date ediSendTime2) {
		this.ediSendTime2 = ediSendTime2;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EDI_SEND_TIME3", length = 7)
	public Date getEdiSendTime3() {
		return this.ediSendTime3;
	}

	public void setEdiSendTime3(Date ediSendTime3) {
		this.ediSendTime3 = ediSendTime3;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EDI_SEND_TIME4", length = 7)
	public Date getEdiSendTime4() {
		return this.ediSendTime4;
	}

	public void setEdiSendTime4(Date ediSendTime4) {
		this.ediSendTime4 = ediSendTime4;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EDI_SEND_TIME5", length = 7)
	public Date getEdiSendTime5() {
		return this.ediSendTime5;
	}

	public void setEdiSendTime5(Date ediSendTime5) {
		this.ediSendTime5 = ediSendTime5;
	}

	@Type(type = "yes_no")
	@Column(name = "ERP_CANCEL_FLAG", length = 10)
	public Boolean getErpCancelFlag() {
		return this.erpCancelFlag;
	}

	public void setErpCancelFlag(Boolean erpCancelFlag) {
		this.erpCancelFlag = erpCancelFlag;
	}

	@Column(name = "H_EDI_01", length = 200)
	public String getHEdi01() {
		return this.HEdi01;
	}

	public void setHEdi01(String HEdi01) {
		this.HEdi01 = HEdi01;
	}

	@Column(name = "H_EDI_02", length = 200)
	public String getHEdi02() {
		return this.HEdi02;
	}

	public void setHEdi02(String HEdi02) {
		this.HEdi02 = HEdi02;
	}

	@Column(name = "H_EDI_03", length = 200)
	public String getHEdi03() {
		return this.HEdi03;
	}

	public void setHEdi03(String HEdi03) {
		this.HEdi03 = HEdi03;
	}

	@Column(name = "H_EDI_04", length = 200)
	public String getHEdi04() {
		return this.HEdi04;
	}

	public void setHEdi04(String HEdi04) {
		this.HEdi04 = HEdi04;
	}

	@Column(name = "H_EDI_05", length = 200)
	public String getHEdi05() {
		return this.HEdi05;
	}

	public void setHEdi05(String HEdi05) {
		this.HEdi05 = HEdi05;
	}

	@Column(name = "H_EDI_06", length = 200)
	public String getHEdi06() {
		return this.HEdi06;
	}

	public void setHEdi06(String HEdi06) {
		this.HEdi06 = HEdi06;
	}

	@Column(name = "H_EDI_07", length = 200)
	public String getHEdi07() {
		return this.HEdi07;
	}

	public void setHEdi07(String HEdi07) {
		this.HEdi07 = HEdi07;
	}

	@Column(name = "H_EDI_08", length = 200)
	public String getHEdi08() {
		return this.HEdi08;
	}

	public void setHEdi08(String HEdi08) {
		this.HEdi08 = HEdi08;
	}

	@Column(name = "H_EDI_09", precision = 18, scale = 8)
	public Double getHEdi09() {
		return this.HEdi09;
	}

	public void setHEdi09(Double HEdi09) {
		this.HEdi09 = HEdi09;
	}

	@Column(name = "H_EDI_10", precision = 18, scale = 8)
	public Double getHEdi10() {
		return this.HEdi10;
	}

	public void setHEdi10(Double HEdi10) {
		this.HEdi10 = HEdi10;
	}

	@Column(name = "USERDEFINE1", length = 200)
	public String getUserdefine1() {
		return this.userdefine1;
	}

	public void setUserdefine1(String userdefine1) {
		this.userdefine1 = userdefine1;
	}

	@Column(name = "USERDEFINE2", length = 200)
	public String getUserdefine2() {
		return this.userdefine2;
	}

	public void setUserdefine2(String userdefine2) {
		this.userdefine2 = userdefine2;
	}

	@Column(name = "USERDEFINE3", length = 200)
	public String getUserdefine3() {
		return this.userdefine3;
	}

	public void setUserdefine3(String userdefine3) {
		this.userdefine3 = userdefine3;
	}

	@Column(name = "USERDEFINE4", length = 200)
	public String getUserdefine4() {
		return this.userdefine4;
	}

	public void setUserdefine4(String userdefine4) {
		this.userdefine4 = userdefine4;
	}

	@Column(name = "USERDEFINE5", length = 200)
	public String getUserdefine5() {
		return this.userdefine5;
	}

	public void setUserdefine5(String userdefine5) {
		this.userdefine5 = userdefine5;
	}

	@Column(name = "USERDEFINE6", length = 200)
	public String getUserdefine6() {
		return this.userdefine6;
	}

	public void setUserdefine6(String userdefine6) {
		this.userdefine6 = userdefine6;
	}

	@Column(name = "NOTES", length = 4000)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tdoOrderMaster", cascade = CascadeType.REMOVE)
	public Set<TdoOrderDetails> getTdoOrderDetailses() {
		return this.tdoOrderDetailses;
	}

	public void setTdoOrderDetailses(Set<TdoOrderDetails> tdoOrderDetailses) {
		this.tdoOrderDetailses = tdoOrderDetailses;
	}

}
